name: FirebaseDeploy

on:
  push:
    branches: [ master ]

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    container: devillex/docker-firebase:latest
    name: Deploy Cloud Functions
    steps:
      - uses: actions/checkout@v2

      - name: Define functions variables
        run: |
          firebase functions:config:set twitter.key="$TWITTER_CLIENT_KEY" -P spott-ly --token $FIREBASE_TOKEN
          firebase functions:config:set twitter.secret="$TWITTER_CLIENT_SECRET" -P spott-ly --token $FIREBASE_TOKEN
          firebase functions:config:set spotify.id="$VUE_APP_SPOTIFY_CLIENT_ID" -P spott-ly --token $FIREBASE_TOKEN
          firebase functions:config:set spotify.secret="$SPOTIFY_CLIENT_SECRET" -P spott-ly --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          TWITTER_CLIENT_KEY: ${{ secrets.TWITTER_CLIENT_KEY }}
          TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
          VUE_APP_SPOTIFY_CLIENT_ID: ${{ secrets.VUE_APP_SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

      - name: Install dependencies
        run: npm ci && cd firebase/functions && npm ci

      - name: Deploy functions
        run: cd firebase && firebase deploy --only functions -P spott-ly --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy_hosting:
    runs-on: ubuntu-latest
    container: devillex/docker-firebase:latest
    name: Deploy Front End
    steps:
      - uses: actions/checkout@v2

      - name: Create .env.local file
        run: |
          echo "VUE_APP_APP_ID=$VUE_APP_APP_ID" >> .env.local
          echo "VUE_APP_API_KEY=$VUE_APP_API_KEY" >> .env.local
          echo "VUE_APP_PROJECT_ID=$VUE_APP_PROJECT_ID" >> .env.local
          echo "VUE_APP_AUTH_DOMAIN=$VUE_APP_AUTH_DOMAIN" >> .env.local
          echo "VUE_APP_DATABASE_URL=$VUE_APP_DATABASE_URL" >> .env.local
          echo "VUE_APP_STORAGE_BUCKET=$VUE_APP_STORAGE_BUCKET" >> .env.local
          echo "VUE_APP_MEASUREMENT_ID=$VUE_APP_MEASUREMENT_ID" >> .env.local
          echo "VUE_APP_SPOTIFY_CLIENT_ID=$VUE_APP_SPOTIFY_CLIENT_ID" >> .env.local
          echo "VUE_APP_MESSAGING_SENDER_ID=$VUE_APP_MESSAGING_SENDER_ID" >> .env.local
        env:
          VUE_APP_APP_ID: ${{ secrets.VUE_APP_APP_ID }}
          VUE_APP_API_KEY: ${{ secrets.VUE_APP_API_KEY }}
          VUE_APP_PROJECT_ID: ${{ secrets.VUE_APP_PROJECT_ID }}
          VUE_APP_AUTH_DOMAIN: ${{ secrets.VUE_APP_AUTH_DOMAIN }}
          VUE_APP_DATABASE_URL: ${{ secrets.VUE_APP_DATABASE_URL }}
          VUE_APP_STORAGE_BUCKET: ${{ secrets.VUE_APP_STORAGE_BUCKET }}
          VUE_APP_MEASUREMENT_ID: ${{ secrets.VUE_APP_MEASUREMENT_ID }}
          VUE_APP_SPOTIFY_CLIENT_ID: ${{ secrets.VUE_APP_SPOTIFY_CLIENT_ID }}
          VUE_APP_MESSAGING_SENDER_ID: ${{ secrets.VUE_APP_MESSAGING_SENDER_ID }}

      - name: Install dependencies
        run: npm ci
      
      - name: Build static files
        run: npm run build

      - name: Copy statics to firebase public directory
        run: mkdir firebase/public && cp -a dist/* firebase/public/

      - name: Deploy hosting
        run: cd firebase && firebase deploy -P spott-ly --token $FIREBASE_TOKEN --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
