name: S3 Deploy

on:
  push:
    branches: [ status ]

jobs:
  deploy_front:
    runs-on: ubuntu-latest
    name: Deploy Front End on S3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cria aquivo .env.local
        run: |
          echo "VUE_APP_APP_ID=$VUE_APP_APP_ID" >> .env.local
          echo "VUE_APP_API_KEY=$VUE_APP_API_KEY" >> .env.local
          echo "VUE_APP_PROJECT_ID=$VUE_APP_PROJECT_ID" >> .env.local
          echo "VUE_APP_AUTH_DOMAIN=$VUE_APP_AUTH_DOMAIN" >> .env.local
          echo "VUE_APP_DATABASE_URL=$VUE_APP_DATABASE_URL" >> .env.local
          echo "VUE_APP_STORAGE_BUCKET=$VUE_APP_STORAGE_BUCKET" >> .env.local
          echo "VUE_APP_MEASUREMENT_ID=$VUE_APP_MEASUREMENT_ID" >> .env.local
          echo "VUE_APP_SPOTIFY_CLIENT_ID=$VUE_APP_SPOTIFY_CLIENT_ID" >> .env.local
          echo "VUE_APP_FIREBASE_ADMIN_UID=$VUE_APP_FIREBASE_ADMIN_UID" >> .env.local
          echo "VUE_APP_MESSAGING_SENDER_ID=$VUE_APP_MESSAGING_SENDER_ID" >> .env.local
        env:
          VUE_APP_APP_ID: ${{ secrets.VUE_APP_APP_ID }}
          VUE_APP_API_KEY: ${{ secrets.VUE_APP_API_KEY }}
          VUE_APP_PROJECT_ID: ${{ secrets.VUE_APP_PROJECT_ID }}
          VUE_APP_AUTH_DOMAIN: ${{ secrets.VUE_APP_AUTH_DOMAIN }}
          VUE_APP_DATABASE_URL: ${{ secrets.VUE_APP_DATABASE_URL }}
          VUE_APP_STORAGE_BUCKET: ${{ secrets.VUE_APP_STORAGE_BUCKET }}
          VUE_APP_MEASUREMENT_ID: ${{ secrets.VUE_APP_MEASUREMENT_ID }}
          VUE_APP_FIREBASE_ADMIN_UID: ${{ secrets.FIREBASE_ADMIN_UID }}
          VUE_APP_SPOTIFY_CLIENT_ID: ${{ secrets.VUE_APP_SPOTIFY_CLIENT_ID }}
          VUE_APP_MESSAGING_SENDER_ID: ${{ secrets.VUE_APP_MESSAGING_SENDER_ID }}

      - name: Adiciona node
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0

      - name: Instala dependências
        run: npm ci
      
      - name: Compila arquivos estáticos
        run: npm run build

      - name: Configura credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copia arquivos para o bucket
        run: aws s3 cp ./dist s3://spottly-status --recursive --acl public-read-write